name = "secure-worker"
type = "javascript"
account_id = "your_account_id"
compatibility_date = "2024-03-01"

[env.production]
routes = ["https://tunnel.mywebhosting.site/secure*"]

r2_buckets = [
  { binding = "FLAGS_BUCKET", bucket_name = "flags" }
]
