name = "worker-return-https"
type = "javascript"
account_id = "b62cf582886e255d6968868ac6923037"
workers_dev = true
main = "src/index.js"

routes = [
  "https://tunnel.mywebhosting.site/secure*"
]

r2_buckets = [
  { binding = "FLAG_BUCKET", bucket_name = "flags-private", preview_bucket_name = "flags-private" }
]
